In [1]:
import pickle
import pandas as pd
import numpy as np
from sklearn.model_selection import cross_validate
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression, LogisticRegressionCV
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler, PowerTransformer
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

In [2]:
def recognizeSearcher(params, feats, featType):
    
    tnOva = 0
    fpOva = 0
    fnOva = 0
    tpOva = 0
    testAccOva = 0
    nSplits = 5
    x = 0
    
    accByNum = []
    outputAll = []
    outputQ = []

    kfold = KFold(n_splits=nSplits, random_state=20210530, shuffle=True)
    
    randomNumber = 20210530 #(open random number)
    
    X = SWC[feats]
    y = SWC['class']
   
    if params['scaler']:
        if params['classWeight']:
            tune_pipe = Pipeline([
            ('standardize', params['scaler']),
            ('classify', RandomForestClassifier(n_estimators=params['numEstimators'], bootstrap = params['bootStrap'],
                                                criterion= params['criterion'], class_weight = params['classWeight'], 
                                                random_state= randomNumber, n_jobs = -1))
            ])
        else:
                        tune_pipe = Pipeline([
            ('standardize', params['scaler']),
            ('classify', RandomForestClassifier(n_estimators=params['numEstimators'], bootstrap = params['bootStrap'],
                                                criterion= params['criterion'], random_state= randomNumber, n_jobs = -1))
            ])
    else:
        if params['classWeight']:
            tune_pipe = Pipeline([
            ('classify', RandomForestClassifier(n_estimators=params['numEstimators'], bootstrap = params['bootStrap'],
                                                criterion= params['criterion'], class_weight = params['classWeight'], 
                                                random_state= randomNumber, n_jobs = -1))
            ])
        else:
                        tune_pipe = Pipeline([
            ('classify', RandomForestClassifier(n_estimators=params['numEstimators'], bootstrap = params['bootStrap'],
                                                criterion= params['criterion'], random_state= randomNumber, n_jobs = -1))
            ])
                

    for train_index, test_index in kfold.split(X):

        rng = np.random.RandomState(randomNumber)
    
        trainSQS = SQS.sample(frac=0.20, random_state=rng)
        test_mask = pd.Series(True, index=SQS.index)
        test_mask[trainSQS.index] = False
        test = SQS[test_mask].copy()

        
        subTrain_x = trainSQS[feats]
        subTrain_y = trainSQS['class']
        
        
        X_train, X_test = X.iloc[train_index], X.iloc[test_index]
        y_train, y_test = y.iloc[train_index], y.iloc[test_index]
        X_train = pd.concat([X_train,subTrain_x])
        y_train = pd.concat([y_train,subTrain_y])
        X_train = X_train.fillna(0)
        tune_pipe.fit(X_train, y_train)

        testAccOva +=  accuracy_score(test['class'], tune_pipe.predict(test[feats]))
        tn, fp, fn, tp = confusion_matrix(test['class'], tune_pipe.predict(test[feats])).ravel()
        tnOva += tn
        fpOva += fp
        fnOva += fn
        tpOva += tp
        outputAll.append(tune_pipe.predict(test[feats]))

        
    pickle.dump( outputAll, open( "Pickles/OutputAll" + str(featType) + "SQS.p", "wb" ) )

   
    results = [featType, round(testAccOva/5,3), tnOva/5, fpOva/5, round(((tnOva/5)/((tnOva/5)+ (fpOva/5))),3), fnOva/5, tpOva/5,round(((tpOva/5)/((tpOva/5)+ (fnOva/5))),3),]
    return results

# Create Test and Train

In [3]:
SWC = pickle.load( open( "Pickles/SWCFeatNoTune.p", "rb" ) )
SQS =  pickle.load( open( "../FeatureExtraction/DataSets/SQSFeatures/SQSFeat.p", "rb" ) )
bestParameters = pickle.load( open( "Pickles/BestParam.p", "rb" ) )

In [4]:
SQS

,queryDistance,timeQueries,repeatQueries,repeatClicks,clickDistance,meanClickPosition,numClicks,numClicksPerQuery,numQueries,timeClicks,...,net,org,edu,gov,http,AND,OR,quotes,inter,class
0,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,...,0,0,0,0,0,0,0,0,0,0
1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,...,0,0,0,0,0,0,0,0,0,0
2,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,...,0,0,0,0,0,0,0,0,0,0
3,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,...,0,0,0,0,0,0,0,0,0,0
4,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1500,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,...,0,0,0,0,0,0,0,0,1,1
1501,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,...,0,0,0,0,0,0,0,0,1,1
1502,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,...,0,0,0,0,0,0,0,1,0,1
1503,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,...,0,0,0,0,0,0,0,0,1,1
1504,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,...,0,0,0,0,0,0,0,0,1,1

In [5]:
features = list(SQS.columns)
features.remove('class')
features.remove('Filename')

In [6]:
features

['queryDistance',
 'timeQueries',
 'repeatQueries',
 'repeatClicks',
 'clickDistance',
 'meanClickPosition',
 'numClicks',
 'numClicksPerQuery',
 'numQueries',
 'timeClicks',
 'uniqueQueries',
 'allSameClicks',
 'uniqueClicks',
 'allSameQueries',
 'cc',
 'cd',
 'dt',
 'ex',
 'fw',
 'in',
 'jj',
 'jjr',
 'jjs',
 'ls',
 'md',
 'nn',
 'nnp',
 'nnps',
 'nns',
 'pdt',
 'pos',
 'prp',
 'rb',
 'rbr',
 'rbs',
 'rp',
 'sym',
 'to',
 'uh',
 'vb',
 'vbd',
 'vbg',
 'vbn',
 'vbp',
 'vbz',
 'wdt',
 'wp',
 'wrb',
 'nn nn',
 'jj nn',
 'nn nns',
 'to vb',
 'jj nns',
 'jj to',
 'nn in',
 'nns in',
 'in nn',
 'dt nn',
 'jj nn nn',
 'nn nn nn',
 'jj to vb',
 'nn nn nns',
 'to vb nn',
 ' Level0',
 ' Level1',
 ' Level2',
 ' Level3',
 ' Level4',
 ' Level5',
 ' Level6',
 ' Level7',
 ' MeanLevel',
 'totalSyl',
 'avgSyl',
 'simWords',
 'comWords',
 'greatestSyl',
 'leastSyl',
 'numChars',
 'numWords',
 'avgLenWord',
 'ld',
 'ls1',
 'ls2',
 'vs1',
 'vs2',
 'cvs1',
 'ndw',
 'ttr',
 'cttr',
 'rttr',
 'logttr',
 'lv',
 'vv1',
 'svv1',
 'cvv1',
 'vv2',
 'nv',
 'adjv',
 'numSpellingErrors',
 'offByOne',
 'kidsError',
 'punct',
 'casing',
 'coreVocab',
 'nonCoreVocab',
 'vocabMin',
 'vocabMax',
 'queryComplexity',
 'addVocab',
 'SVEN',
 'top250All',
 'top250avgAll',
 'top250avgNotAll',
 'top250AllNA',
 'top250avgAllNA',
 'top250avgNotAllNA',
 'top50bi',
 'top50biAvg',
 'top50biNot',
 'top50biNA',
 'top50biavgNA',
 'top50biNotNA',
 'tfidfAll',
 'tfidf',
 'tfidfNA',
 'stopCount',
 'com',
 'net',
 'org',
 'edu',
 'gov',
 'http',
 'AND',
 'OR',
 'quotes',
 'inter']

In [7]:
P3Feats = ['ld',
 'ls1',
 'ls2',
 'vs1',
 'vs2',
 'cvs1',
 'ndw',
 'ttr',
 'cttr',
 'rttr',
 'logttr',
 'lv',
 'vv1',
 'svv1',
 'cvv1',
 'vv2',
 'nv',
 'adjv',
 'coreVocab',
 'nonCoreVocab',
 'vocabMin',
 'vocabMax',
 'queryComplexity',
 'addVocab',
 'SVEN',
 'top250All',
 'top250avgAll',
 'top250avgNotAll',
 'top250AllNA',
 'top250avgAllNA',
 'top250avgNotAllNA',
 'top50bi',
 'top50biAvg',
 'top50biNot',
 'top50biNA',
 'top50biavgNA',
 'top50biNotNA',
 'tfidfAll',
 'tfidf',
 'tfidfNA',
 ]

In [8]:
DC1Feats = ['ndw',
 'ttr',
 'cttr',
 'rttr',
 'logttr',
 'lv',
 'vv1',
 'svv1',
 'cvv1',
 'vv2',
 'nv',
 'adjv',
 'totalSyl',
 'avgSyl',
 'simWords',
 'comWords',
 'greatestSyl',
 'leastSyl',
 'numChars',
 'numWords',
 'avgLenWord',
 'vocabMin',
 'vocabMax',
 'queryComplexity',
 'stopCount',
 'com',
 'net',
 'org',
 'edu',
 'gov',
 'http',
 'AND',
 'OR',
 'quotes',
 'inter',
 'numSpellingErrors',
 'offByOne',
 'kidsError',
 'punct',
 'casing',
 'cc',
 'cd',
 'dt',
 'ex',
 'fw',
 'in',
 'jj',
 'jjr',
 'jjs',
 'ls',
 'md',
 'nn',
 'nnp',
 'nnps',
 'nns',
 'pdt',
 'pos',
 'prp',
 'rb',
 'rbr',
 'rbs',
 'rp',
 'sym',
 'to',
 'uh',
 'vb',
 'vbd',
 'vbg',
 'vbn',
 'vbp',
 'vbz',
 'wdt',
 'wp',
 'wrb',
 'nn nn',
 'jj nn',
 'nn nns',
 'to vb',
 'jj nns',
 'jj to',
 'nn in',
 'nns in',
 'in nn',
 'dt nn',
 'jj nn nn',
 'nn nn nn',
 'jj to vb',
 'nn nn nns',
 'to vb nn',]

In [9]:
TextFeat = ['cc',
 'cd',
 'dt',
 'ex',
 'fw',
 'in',
 'jj',
 'jjr',
 'jjs',
 'ls',
 'md',
 'nn',
 'nnp',
 'nnps',
 'nns',
 'pdt',
 'pos',
 'prp',
 'rb',
 'rbr',
 'rbs',
 'rp',
 'sym',
 'to',
 'uh',
 'vb',
 'vbd',
 'vbg',
 'vbn',
 'vbp',
 'vbz',
 'wdt',
 'wp',
 'wrb',
 'nn nn',
 'jj nn',
 'nn nns',
 'to vb',
 'jj nns',
 'jj to',
 'nn in',
 'nns in',
 'in nn',
 'dt nn',
 'jj nn nn',
 'nn nn nn',
 'jj to vb',
 'nn nn nns',
 'to vb nn',
 ' Level0',
 ' Level1',
 ' Level2',
 ' Level3',
 ' Level4',
 ' Level5',
 ' Level6',
 ' Level7',
 ' MeanLevel',
 'totalSyl',
 'avgSyl',
 'simWords',
 'comWords',
 'greatestSyl',
 'leastSyl',
 'numChars',
 'numWords',
 'avgLenWord',
 'ld',
 'ls1',
 'ls2',
 'vs1',
 'vs2',
 'cvs1',
 'ndw',
 'ttr',
 'cttr',
 'rttr',
 'logttr',
 'lv',
 'vv1',
 'svv1',
 'cvv1',
 'vv2',
 'nv',
 'adjv',
 'numSpellingErrors',
 'offByOne',
 'kidsError',
 'punct',
 'casing',
 'coreVocab',
 'nonCoreVocab',
 'vocabMin',
 'queryComplexity',
 'addVocab',
 'vocabMax',
 'SVEN',
 'top250All',
 'top250avgAll',
 'top250avgNotAll',
 'top250AllNA',
 'top250avgAllNA',
 'top250avgNotAllNA',
 'top50bi',
 'top50biAvg',
 'top50biNot',
 'top50biNA',
 'top50biavgNA',
 'top50biNotNA',
 'tfidfAll',
 'tfidf',
 'tfidfNA',
 'stopCount',
 'com',
 'net',
 'org',
 'edu',
 'gov',
 'http',
 'AND',
 'OR',
 'quotes',
 'inter']

In [10]:
SessionFeats = ['repeatClicks',
 'clickDistance',
 'meanClickPosition',
 'numClicks',
 'numClicksPerQuery',
 'numQueries',
 'timeClicks',
 'uniqueQueries',
 'allSameClicks',
 'uniqueClicks',
 'allSameQueries',
 'queryDistance',
 'timeQueries',
 'repeatQueries']

In [11]:
RYSe = recognizeSearcher(bestParameters, features, 'RYSe')
P3Results = recognizeSearcher(bestParameters, P3Feats, 'P3')
DC1Results = recognizeSearcher(bestParameters, DC1Feats, 'DC1')
textResults = recognizeSearcher(bestParameters, TextFeat, 'TextBased')
sessionResults = recognizeSearcher(bestParameters, SessionFeats, 'SessionBased')

In [12]:
RYSe

['RYSe', 0.879, 958.6, 3.4, 0.996, 142.8, 99.2, 0.41]

In [13]:
P3Results

['P3', 0.814, 957.8, 4.2, 0.996, 219.8, 22.2, 0.092]

In [14]:
DC1Results

['DC1', 0.835, 953.6, 8.4, 0.991, 190.8, 51.2, 0.212]

In [15]:
textResults

['TextBased', 0.823, 958.4, 3.6, 0.996, 209.8, 32.2, 0.133]

In [16]:
sessionResults

['SessionBased', 0.799, 962.0, 0.0, 1.0, 242.0, 0.0, 0.0]

In [17]:
allResults = pd.DataFrame(data = [RYSe,P3Results,DC1Results,textResults,sessionResults  ], columns = ["Type","Acc", "TN", "FP", "TNR", "FN", "TP", "TPR"])

In [18]:
allResults

           Type    Acc     TN   FP    TNR     FN    TP    TPR
0          RYSe  0.879  958.6  3.4  0.996  142.8  99.2  0.410
1            P3  0.814  957.8  4.2  0.996  219.8  22.2  0.092
2           DC1  0.835  953.6  8.4  0.991  190.8  51.2  0.212
3     TextBased  0.823  958.4  3.6  0.996  209.8  32.2  0.133
4  SessionBased  0.799  962.0  0.0  1.000  242.0   0.0  0.000

In [19]:
pickle.dump( allResults, open( "Pickles/AblationSQS.p", "wb" ) )