# Comparison

In [1]:
import pickle
import pandas as pd
import numpy as np
from sklearn.model_selection import cross_validate
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression, LogisticRegressionCV
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, PowerTransformer
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchCV
from tqdm import tqdm


rng = np.random.RandomState(20210414)

In [2]:
SWCAll =  pickle.load( open( "../FeatureExtraction/DataSets/SWCFeatures/SWCFeat.p", "rb" ) )
searchFeatSWC = pickle.load( open( "../FeatureExtraction/Pickles/SearchFeatSWC.p", "rb" ) )

In [3]:
searchFeatSWC[searchFeatSWC['sID'] == 7]

,sID,query,timestamp,click,website,type,order,class,queryDistance,timeQueries,...,allSameQueries,repeatClicks,uniqueClicks,allSameClicks,timeClicks,clickDistance,numQueries,numClicks,meanClickPosition,numClicksPerQuery
42,7,prom hair styles,0,,,Q,0,1,0,0.0,...,1,0,7,0,0.000000,-1,3,9.0,41.888889,0.333333
43,7,prom hair styles,91,,,Q,1,1,0,91.0,...,1,0,7,0,0.000000,-1,3,9.0,41.888889,0.333333
44,7,prom hair styles,91,1,http://hairstyles.free-beauty-tips.com,C,2,1,-1,-1.0,...,1,0,7,0,0.000000,29,3,9.0,41.888889,0.333333
45,7,prom hair styles,91,3,http://www.prom-hairstyles.org,C,3,1,-1,-1.0,...,1,0,7,0,0.000000,17,3,9.0,41.888889,0.333333
46,7,prom hair styles,91,4,http://www.hairboutique.com,C,4,1,-1,-1.0,...,1,0,7,0,0.000000,20,3,9.0,41.888889,0.333333
47,7,prom hair styles,164,,,Q,5,1,0,73.0,...,1,0,7,0,119.000000,-1,3,9.0,41.888889,0.333333
48,7,prom hair styles,164,57,http://www.more-hairstyles.com,C,6,1,-1,-1.0,...,1,0,7,0,0.000000,19,3,9.0,41.888889,0.333333
49,7,prom hair styles,164,59,http://www.hair-styles-cuts-and-dos.com,C,7,1,-1,-1.0,...,1,0,7,0,0.000000,28,3,9.0,41.888889,0.333333
50,7,prom hair styles,164,61,http://3-ibm.com,C,8,1,-1,-1.0,...,1,0,7,0,0.000000,16,3,9.0,41.888889,0.333333
51,7,prom hair styles,164,63,http://www.prom-hairstyles.org,C,9,1,-1,-1.0,...,1,1,7,0,55.500000,17,3,9.0,41.888889,0.333333
52,7,prom hair styles,164,64,http://www.lovelandia.com,C,10,1,-1,-1.0,...,1,0,7,0,16.666667,23,3,9.0,41.888889,0.333333
53,7,prom hair styles,164,65,http://www.lovelandia.com,C,11,1,-1,-1.0,...,1,1,7,0,0.000000,23,3,9.0,41.888889,0.333333

In [4]:
FlatALL = pickle.load( open( "../../thesis/Classification/FlatALL.p", "rb" ) )
FlatALLCols = FlatALL.columns.tolist()

In [5]:
for column in SWCAll.columns.tolist():
    if column in FlatALLCols:
        if(SWCAll[column].equals(FlatALL[column]) == False):
            print(column, False)

top50bi False
top50biNot False
top50biNA False
top50biavgNA False
top50biNotNA False
tfidf False
tfidfNA False
repeatClicks False
clickDistance False
meanClickPosition False
numQueries False
timeClicks False
queryDistance False
timeQueries False
repeatQueries False

In [6]:
numR = (FlatALL['inter'] == SWCAll['inter'])

In [7]:
FlatALL['inter'] == SWCAll['inter']

sID
0        True
1        True
2        True
3        True
4        True
         ...
39895    True
39896    True
39897    True
39898    True
39899    True
Name: inter, Length: 39370, dtype: bool

In [8]:
numR[numR == False]

Series([], Name: inter, dtype: bool)

In [9]:
FlatALL.iloc[56]['inter']

1.0

In [10]:
SWCAll.iloc[56]['inter']

1.0

In [11]:
searchFeatSWC[searchFeatSWC['sID'] == 56]

,sID,query,timestamp,click,website,type,order,class,queryDistance,timeQueries,...,allSameQueries,repeatClicks,uniqueClicks,allSameClicks,timeClicks,clickDistance,numQueries,numClicks,meanClickPosition,numClicksPerQuery
337,56,what is 4h,0,,,Q,0,1,0,0.0,...,-1,0,2,0,0.000000,-1,1,2.0,6.5,0.5
338,56,what is 4h,0,3,http://www.4husa.org,C,1,1,-1,-1.0,...,-1,0,2,0,34.000000,17,1,2.0,6.5,0.5
339,56,what is 4h,0,10,http://www.uri.edu,C,2,1,-1,-1.0,...,-1,0,2,0,69.333333,16,1,2.0,6.5,0.5

In [12]:
SWCAll['stopCount'].head(10)

sID
0    1.000000
1    0.000000
2    0.333333
3    0.000000
4    1.000000
5    0.000000
6    0.500000
7    0.000000
8    0.000000
9    0.000000
Name: stopCount, dtype: float64

In [13]:
FlatALL['stopCount'].head(10)

sID
0    1.000000
1    0.000000
2    0.333333
3    0.000000
4    1.000000
5    0.000000
6    0.500000
7    0.000000
8    0.000000
9    0.000000
Name: stopCount, dtype: float64

In [14]:
numQ = (FlatALL['numQ'] == SWCAll['numQ'])

KeyError: 'numQ'

In [ ]:
numQ[numQ == False]

In [ ]:
FlatALL['stopCount']

In [ ]:
SWCAll['stopCount']